export default {
    DBURI: 'mongodb://localhost/sfsDb',
    BASEURL: 'http://localhost:3000',
    HOST: 'XXXXXXXXXXXXXXXXXXX',
    USERNAME: 'XXXXXXXXXXXXXXXX',
    PASS: 'XXXXXXXXXXXXXXX',
    JWT_SECRET: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
}